### ISSUE TITLE
Fails to activate on 3.2.7

### ISSUE THREAD

**Issue by Lightzy** [3D-I/pfbbcode#4]
I have a phpBB forum that began as 3.2.3, but I updated it to 3.2.7 to use this extension, but I'm still getting the same error message. Can you help?

![image](https://user-images.githubusercontent.com/54639152/63877711-06699f80-c9c0-11e9-8242-0aed9097a7ec.png)
![image](https://user-images.githubusercontent.com/54639152/63877770-24cf9b00-c9c0-11e9-8c67-fbf646e6e42b.png)

**Comment by 3D-I** [comment]
Ask for support at phpbb DOT com, that's an issue of your update.
